# Description: This playbook installs avarious shell utilities on Ubuntu
#
# Example on localhost:   sudo ansible-playbook ./shell_utils.playbook.yml

- name: Install utilities on Ubuntu
  hosts: localhost
  become: yes
  tasks:
    - name: Update apt package cache
      apt:
        update_cache: yes

    - name: Install yq v4.48.1
      ansible.builtin.get_url:
        url: https://github.com/mikefarah/yq/releases/download/v4.48.1/yq_linux_amd64
        dest: /usr/local/bin/yq
        mode: '0755'
